server:
  port: ${APP_PORT:8181}
  servlet:
    context-path: /api/be-service
spring:
  application:
    name: DATN_BE
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:123456}
    hikari:
      schema: store
      auto-commit: true
      max-lifetime: ${DB_CONNECTION_LIFE_TIME:30000}
      idle-timeout: ${DB_IDLE_TIME_OUT:30000}
      minimum-idle: ${DB_CONNECTION_MIN:2}
      maximum-pool-size: ${DB_CONNECTION_MAX:5}
      connection-timeout: ${CONNECTION_TIME_OUT:20000}
      connection-test-query: ${POSTGRES_VALIDATION_QUERY_POOL:SELECT 1}
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:thanhcnps37081@fpt.edu.vn}
    password: ${MAIL_PASSWORD:ldor aver bwwy ydll}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

jwt:
  secret: ${JWT_SECRET:your-secret-key-change-in-production-env-this-is-very-important-keep-it-safe-and-secure}
  expiration: ${JWT_EXPIRATION:8640000000}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000}

vnpay:
  tmn-code: ${VNPAY_TMN_CODE:IF0C7500}
  hash-secret: ${VNPAY_HASH_SECRET:592FZ1KQUWAW2V3GXMBZ4D3WVI3AUYKT}
  url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  return-url: ${VNPAY_RETURN_URL:http://localhost:5173/payment/vnpay-return}
  version: "2.1.0"
  command: pay
  locale: vn
  currency: VND

app:
  mail:
    from: ${MAIL_FROM:${MAIL_USERNAME:noreply@fpoly.edu.vn}}
    frontend-url: ${FRONTEND_URL:http://localhost:5173}
